services:
  bot:
    image: dog_bot
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - dog_bot
    container_name: dog_bot
    restart: always
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    container_name: dog-db
    restart: always
    ports:
      - '5433:5432'

volumes:
  db_data:
